---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: pcf-attendee-service-code

outputs:
- name: package-output

run:
  path: pcf-attendee-service-code/ci/tasks/package.sh

