---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "latest"

params:
  ATTENDEE_SERVICE_URL:

inputs:
- name: pcf-attendee-service-code

run:
  path: pcf-attendee-service-code/ci/tasks/smoke-test.sh