---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: pcf-attendee-service-code

run:
  path: pcf-attendee-service-code/ci/tasks/test.sh
